default: true

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013
MD013: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md033
MD033: false

# https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md034
MD034: false
