title: "Okta を Terraform と GitHub Actions を使ってコード管理するチュートリアル"
summary: "IdP である Okta を公式の Terraform Provider を使ってコード管理+設定の監視をできるようにします。"
topics: ["Okta", "Terraform", "GitHubActions"]
published: true
price: 0 # 有料の場合200〜5000
toc_depth: 3
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01_introduction
  - 02_requirement
  - 03_setup
  - 04_terraform-tutorial
  - 05_terraform-okta_01
  - 06_terraform-okta_02
  - 07_github-action_01
  - 08_github-action_02
